# Generated by Django 4.2.1 on 2025-03-07 04:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('students', '0001_initial'),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Plastic kartasi', 'Plastic kartasi'), ('Naqd', 'Naqd'), ('Payme', 'Payme'), ('Click', 'Click')], max_length=255)),
                ('amount', models.BigIntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(blank=True, null=True)),
                ('chek', models.FileField(upload_to='chek/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('educenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.educenter')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_groups', to='groups.groups')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
        ),
    ]
