# Generated by Django 4.2.1 on 2025-02-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='type',
            field=models.CharField(choices=[('Plastic kartasi', 'Plastic kartasi'), ('Bank hisobi', 'Bank hisobi'), ('Naqd', 'Naqd'), ('Payme', 'Payme'), ('Click', 'Click')], max_length=255),
        ),
    ]
