# Generated by Django 4.2.1 on 2025-03-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payments_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.CharField(max_length=255),
        ),
    ]
