# Generated by Django 4.2.1 on 2025-03-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payments_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.BigIntegerField(),
        ),
    ]
