# Generated by Django 4.2.1 on 2025-02-07 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, default='avatar/default.jpg', null=True, upload_to='avatar/')),
                ('gender', models.CharField(choices=[('Ayol', 'Ayol'), ('Erkak', 'Erkak')], default='Erkak', max_length=50)),
                ('birth_day', models.DateField()),
                ('status', models.CharField(choices=[('Aktiv', 'Aktiv'), ('Aktiv emas', 'Aktiv emas')], default='Aktiv', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('educenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.educenter')),
            ],
        ),
    ]
