services:
  db:
    image: postgres:16
    container_name: edurise_db
    restart: always
    environment:
      POSTGRES_DB: edurisedb
      POSTGRES_USER: edurise_user
      POSTGRES_PASSWORD: edurise_password
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U edurise_user -d edurisedb" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: edurise_web
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn app.wsgi:application --bind 0.0.0.0:8008 --workers=4"
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8008:8008"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://edurise_user:edurise_password@db:5432/edurisedb
volumes:
  pg_data:
  static_volume:
