version: '3.11'

services:
  web:
    build: .
    command: "sh ./entrypoint.sh"
    ports:
      - "8082:8000"
    volumes:
      - "./:/code"
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=2309
      - POSTGRES_DB=django
      - POSTGRES_USER=postgres
    volumes:
      - "pgdata:/var/lib/postgresql/data"

volumes:
  pgdata: null
