services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: edurisedb
      POSTGRES_USER: edurise_user
      POSTGRES_PASSWORD: edurise_password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/  # Ma'lumotlarni hostda saqlash
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U edurise_user -d edurisedb" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8008
    volumes:
      - .:/app
    ports:
      - "8008:8008"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://edurise_user:edurise_password@db:5432/edurisedb


