# Generated by Django 4.2.1 on 2025-02-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='created_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
