# Generated by Django 4.2.1 on 2023-06-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="role",
            field=models.IntegerField(
                choices=[
                    (1, "SUPER_ADMIN"),
                    (2, "ADMIN"),
                    (3, "CEO"),
                    (4, "ADMINISTRATOR"),
                    (5, "MANGER"),
                    (6, "CASHER"),
                    (7, "TEACHER"),
                ]
            ),
        ),
    ]
