# Generated by Django 4.2.1 on 2023-06-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_users_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="birth_day",
            field=models.DateField(blank=True, null=True),
        ),
    ]
