# Generated by Django 4.2.1 on 2025-02-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('file', models.ImageField(upload_to='certificates/', verbose_name='Fayil')),
                ('callback', models.CharField(max_length=255, verbose_name='Funcsiya')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikat turlari',
            },
        ),
        migrations.CreateModel(
            name='EduCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(default='logo/default.jpg', upload_to='logo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.BigIntegerField(blank=True, null=True)),
                ('certificates', models.ManyToManyField(to='education.certificatetype', verbose_name='Sertifikatlar')),
            ],
        ),
    ]
