# Generated by Django 4.2.1 on 2023-06-14 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="educenter",
            name="closing_time",
        ),
        migrations.RemoveField(
            model_name="educenter",
            name="opening_time",
        ),
    ]
