# Generated by Django 4.2.1 on 2025-02-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetype',
            name='callback',
            field=models.CharField(max_length=255, verbose_name='Funksiya'),
        ),
        migrations.AlterField(
            model_name='educenter',
            name='certificates',
            field=models.ManyToManyField(blank=True, null=True, to='education.certificatetype', verbose_name='Sertifikatlar'),
        ),
        migrations.AlterField(
            model_name='educenter',
            name='logo',
            field=models.ImageField(blank=True, default='logo/default.jpg', null=True, upload_to='logo/'),
        ),
    ]
