# Generated by Django 4.2.1 on 2025-03-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educenter',
            name='certificate_boolen',
            field=models.BooleanField(default=False, verbose_name='Sertifikat mumkim yoki mumkin emas?'),
        ),
    ]
