# Generated by Django 4.2.1 on 2025-02-27 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_certificatetype_callback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetype',
            name='educenter_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name="O'quv markaz nomi"),
            preserve_default=False,
        ),
    ]
