# Generated by Django 4.2.1 on 2024-11-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_remove_educenter_closing_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('file', models.ImageField(upload_to='certificates/', verbose_name='Fayil')),
                ('callback', models.CharField(max_length=255, verbose_name='Funcsiya')),
            ],
        ),
        migrations.AddField(
            model_name='educenter',
            name='certificates',
            field=models.ManyToManyField(to='education.certificatetype', verbose_name='Sertifikatlar'),
        ),
    ]
