# Generated by Django 4.2.1 on 2023-06-13 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("education", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "days",
                    models.CharField(
                        choices=[
                            ("Farqi yo'q", "Farqi yo'q"),
                            ("Juft kunlar", "Juft kunlar"),
                            ("Toq kunlar", "Toq kunlar"),
                        ],
                        default="Farqi yo'q",
                        max_length=255,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Ayol", "Ayol"), ("Erkak", "Erkak")],
                        default="Erkak",
                        max_length=50,
                    ),
                ),
                ("birth_day", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.courses",
                    ),
                ),
                (
                    "educenter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="education.educenter",
                    ),
                ),
            ],
        ),
    ]
