# Generated by Django 4.2.1 on 2025-03-07 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.IntegerField(choices=[(30, 30), (40, 40), (60, 60), (90, 90), (120, 120), (180, 180), (240, 240), (280, 280), (300, 300)], default=90)),
                ('month_duration', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('educenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.educenter')),
            ],
        ),
    ]
