# Generated by Django 4.2.1 on 2025-03-07 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('course', models.CharField(max_length=120)),
                ('certificate', models.FileField(upload_to='certificates/')),
                ('certificate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.certificatetype')),
                ('educenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.educenter')),
            ],
        ),
    ]
