# Generated by Django 4.2.1 on 2025-02-25 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_certificatetype_callback_and_more'),
        ('fast_certificate', '0002_fastcertificate_educenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastcertificate',
            name='certificate_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='education.certificatetype'),
            preserve_default=False,
        ),
    ]
