# Generated by Django 4.2.1 on 2025-02-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_certificate', '0004_alter_fastcertificate_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastcertificate',
            name='certificate',
            field=models.FileField(upload_to='certificates/'),
        ),
    ]
