# Generated by Django 4.2.1 on 2025-03-07 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
        ('rooms', '0001_initial'),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('days', models.CharField(choices=[('Toq kunlar', 'Toq kunlar'), ('Juft kunlar', 'Juft kunlar')], max_length=255)),
                ('starting_time', models.TimeField()),
                ('starting_day', models.DateField()),
                ('price', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
                ('educenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_education', to='education.educenter')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_room', to='rooms.rooms')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_teacher', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='groups', to='students.students')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('educenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_journal', to='education.educenter')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groups')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
        ),
    ]
